
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

inhibit_all_warnings!

#消除多源pod警告
install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false, :warn_for_multiple_pod_sources => false

target 'VivaMedi' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
#  use_modular_headers!
  eval(File.open('PodDevExtension.rb').read) if File.exist? 'PodDevExtension.rb'
  
  pod 'YYWebImage'
  #第三方库
  pod 'ReactiveObjC'
#  pod 'SSZipArchive'
  pod 'SDWebImage'
  pod 'FMDB'
  pod 'YYModel'
  pod 'YYImage/WebP'
  pod 'SSZipArchive'

  # Pods for VivaMedi

  target 'VivaMediTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VivaMediUITests' do
    # Pods for testing
  end

end
